Module federation
plone/plone.staticresources pull request #222
Opened 2022-05-17 23:18 UTC by thet

2022-05-17 23:18 UTC, mister-roboto commented
@thet thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2022-05-23 01:26 UTC, thet commented
@jenkins-plone-org please run jobs

2022-05-23 14:53 UTC, petschki requested changes
Somehow `pat-structure` doesn't load stable. I only get the folder_contents view every 4th or 5th reload ...

2022-05-25 08:33 UTC, petschki approved these changes
I cleaned everything and build from scratch ... it seems to me that it does load more often but still not 100% ... anyway good to go for merging this!

2022-06-01 09:20 UTC, merged