Upgrade Mockup
plone/plone.staticresources pull request #251
Opened 2022-11-07 11:06 UTC by thet

2022-11-07 11:06 UTC, mister-roboto commented
@thet thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2022-11-07 11:08 UTC, thet commented
@jenkins-plone-org please run jobs

2022-11-07 11:23 UTC, thet commented
@jenkins-plone-org please run jobs

2022-11-07 12:18 UTC, petschki requested changes
Jenkins is failing ...

2022-11-14 07:56 UTC, petschki commented
@jenkins-plone-org please run jobs

2022-11-14 09:33 UTC, petschki approved these changes
👍🏼

2022-11-14 09:33 UTC, merged